{% set version = "0.6.3" %}

package:
  name: autodiff
  version: {{ version }}

source:
  url: https://github.com/autodiff/autodiff/archive/v{{ version }}.tar.gz
  sha256: afcc21c74c9c20ecf08c53ab82965652438d5bb65d146a2db43795b051c12135

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - ccache  # [unix]
    - clcache  # [win]

  host:
    - python
    - eigen
    - catch2
    - pybind11
    - pybind11-stubgen
    - pybind11-abi

  run:
    - python
    # eigen MUST NOT be added here but installed explicitly by the user if needed

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - autodiff

about:
  home: https://autodiff.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic differentiation in C++ couldn't be simpler.
  doc_url: https://autodiff.github.io
  dev_url: https://github.com/autodiff/autodiff

extra:
  recipe-maintainers:
    - allanleal
