{% set version = "0.5.9" %}

package:
  name: autodiff
  version: {{ version }}

source:
  url: https://github.com/allanleal/autodiff/archive/improve-high-order-derivatives-using-array.tar.gz
  sha256: 62fa8f463b11533212a2b7b3c3a899a89a6a42404da75821fdd59048041892c7
  # url: https://github.com/autodiff/autodiff/archive/v{{ version }}.tar.gz
  # sha256: c746bf611c66acc94113aa4483caf73631216d6db5b511df2b5dcb29a0a4345a

build:
  number: 0
  skip: true  # [win and vc<17]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - ccache  # [unix]
    - catch2

  host:
    - eigen

  run:
    - {{ pin_compatible('eigen', max_pin='x') }}

test:
  files:
    - test/

  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

about:
  home: https://autodiff.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic differentiation in C++ couldn't be simpler.
  doc_url: https://autodiff.github.io
  dev_url: https://github.com/autodiff/autodiff

extra:
  recipe-maintainers:
    - allanleal
