# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iYTQZxbrDJDrr0jatr0nBuwPA+S6yDUA/m8Sg/SfDVIBmt8tesWALLUBdY8oSEqwBPLrdq+0vtonqlAIj+csveySCx6kWy/pR0tA5RUu1PAeBNxLkiFhZe8fxfTBnWhB5mOm+NQcEjNQ/xg9T9JTk27gQVDOK81GOehzLwhPn1TEJ3UYzYBWw6RymUINrZp9FYfi6aIdwGqn65hXetWaM7sRWwztB+6CKneevZdxpjfAt/aBGFzSLdGj2YK4y2mpdUN5Zy9+rCCHihOlZI+pxApqkTHQmYx1Kx9fh4h1xN/MjjKQftTlTqFYw7/vak80cfOKhCYUDI21iiFxne1aLEF66wxnidyUfZWjLe1NDbPjs5p+KeVqGSemnmncr04aWnykije1ijp8cyIwsSxFjcziCrKjIexaseLBGfPDO9mzfDhlldDvfgmbTCSCt330F4U4RJZu1e1vQvl3riTEw4Xz0oOH8yn2HG2B9lZrvnEDFQoyrzcsgrd3D7/l6A59VaJr0IhAsKz8HZEC16TkRq7JbJyvIp7fTSLPo7dJABbt4Ar/o92ET352VGFZ9nFpkhapqrkayyWQlkmskOSqn3GVsf1ZPcUidye1CNOr6U26FOlNEEeEztKBQgOx2g4oQnkxouYmqe7A3CKRInUHACGUg8GnSRBfcU+MTyDh3g0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml